In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [84]:
pd.set_option('display.max_columns', None)

In [85]:
df = pd.read_csv("data/Delivery Dataset.csv")

In [86]:
df.shape

(41944, 20)

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41944 entries, 0 to 41943
Data columns (total 20 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID                           41944 non-null  object
 1   Delivery_person_ID           41944 non-null  object
 2   Delivery_person_Age          40225 non-null  float64
 3   Delivery_person_Ratings      40181 non-null  float64
 4   Restaurant_latitude          41944 non-null  float64
 5   Restaurant_longitude         41944 non-null  float64
 6   Delivery_location_latitude   41944 non-null  float64
 7   Delivery_location_longitude  41944 non-null  float64
 8   Order_Date                   41944 non-null  object
 9   Time_Orderd                  40344 non-null  object
 10  Time_Order_picked            41944 non-null  object
 11  Weather_conditions           41375 non-null  object
 12  Road_traffic_density         41389 non-null  object
 13  Vehicle_condition            41944 non-null  int64
 14  Type_of_order                41944 non-null  object
 15  Type_of_vehicle              41944 non-null  object
 16  multiple_deliveries          41039 non-null  float64
 17  Festival                     41729 non-null  object
 18  City_Type                    40830 non-null  object
 19  Time_taken (min)             41944 non-null  int64
dtypes: float64(7), int64(2), object(11)
memory usage: 6.4+ MB

In [88]:
df.drop(columns="ID" , inplace=True)

In [89]:
round(df.isna().sum()/df.shape[0] * 100 , 2)

Delivery_person_ID             0.00
Delivery_person_Age            4.10
Delivery_person_Ratings        4.20
Restaurant_latitude            0.00
Restaurant_longitude           0.00
Delivery_location_latitude     0.00
Delivery_location_longitude    0.00
Order_Date                     0.00
Time_Orderd                    3.81
Time_Order_picked              0.00
Weather_conditions             1.36
Road_traffic_density           1.32
Vehicle_condition              0.00
Type_of_order                  0.00
Type_of_vehicle                0.00
multiple_deliveries            2.16
Festival                       0.51
City_Type                      2.66
Time_taken (min)               0.00
dtype: float64

In [90]:
df.drop(index= df[df['Delivery_person_ID'].isna()].index , inplace=True)

In [91]:
df.isna().sum()

Delivery_person_ID                0
Delivery_person_Age            1719
Delivery_person_Ratings        1763
Restaurant_latitude               0
Restaurant_longitude              0
Delivery_location_latitude        0
Delivery_location_longitude       0
Order_Date                        0
Time_Orderd                    1600
Time_Order_picked                 0
Weather_conditions              569
Road_traffic_density            555
Vehicle_condition                 0
Type_of_order                     0
Type_of_vehicle                   0
multiple_deliveries             905
Festival                        215
City_Type                      1114
Time_taken (min)                  0
dtype: int64

Fetching Valuable Features from `Delivery_person_ID` 

like:

`JAPRES04DEL01`
- **JAP** → City code →**Jaipur**
- **RES04** → Region / hub / zone → **Zone 04**
- **DEL01** → Delivery person → **Agent 01**

In [92]:
df['Delivery_person_ID']

0           DEHRES17DEL01
1           KOCRES16DEL01
2          PUNERES13DEL03
3          LUDHRES15DEL02
4           KNPRES14DEL02
               ...
41939    RANCHIRES16DEL01
41940       JAPRES04DEL01
41941      CHENRES08DEL03
41942     COIMBRES11DEL01
41943    RANCHIRES09DEL02
Name: Delivery_person_ID, Length: 41944, dtype: object

In [93]:
df['Delivery_person_ID'].str[:-10].unique()

array(['DEH', 'KOC', 'PUNE', 'LUDH', 'KNP', 'MUM', 'MYS', 'HYD', 'KOL',
       'RANCHI', 'COIMB', 'CHEN', 'JAP', 'SUR', 'BANG', 'GOA', 'AGR',
       'ALH', 'BANGR', 'VAD', 'AURG', 'AGRR', 'INDO', 'SURR', 'KOCR',
       'MYSR', 'LUDHR', 'DEHR', 'HYDR', 'MUMR', 'RANCHIR', 'JAPR',
       'INDOR', 'CHENR', 'PUNER', 'VADR', 'COIMBR', 'BHP', 'KNPR', 'GOAR',
       'BHPR', 'AURGR', 'KOLR'], dtype=object)

In [94]:
city = df['Delivery_person_ID'].str[:-10].apply(lambda x : x[:-1] if x.endswith("R") else x)
df.insert(1 , "City" , city)

In [95]:
city_mapping = {
    "INDO": "Indore",
    "BANG": "Bangalore",
    "COIMB": "Coimbatore",
    "CHEN": "Chennai",
    "HYD": "Hyderabad",
    "RANCHI": "Ranchi",
    "MYS": "Mysore",
    "DEH": "Dehradun",
    "KOC": "Kochi",
    "PUNE": "Pune",
    "LUDH": "Ludhiana",
    "KNP": "Kanpur",
    "MUM": "Mumbai",
    "KOL": "Kolkata",
    "JAP": "Jaipur",
    "SUR": "Surat",
    "SU": "Surat",
    "GOA": "Goa",
    "AURG": "Aurangabad",
    "AGR": "Agra",
    "AG": "Agra",
    "VAD": "Vadodara",
    "ALH": "Prayagraj",
    "BHP": "Bhopal"
}

In [96]:
df['City'] = df['City'].map(city_mapping)

In [97]:
df['City'].nunique()

22

In [98]:
df.sample()

,Delivery_person_ID,City,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
22932,HYDRES11DEL01,Hyderabad,30.0,4.3,17.430448,78.418213,17.470448,78.458213,30-03-2022,14:30,14:35,Cloudy,High,2,Snack,motorcycle,1.0,No,Metropolitian,38

In [99]:
zone = df['Delivery_person_ID'].str.split("RES").str[1].str[:2].str.strip()

df.insert(2 , "Zone" , zone)

In [100]:
df.sample()

,Delivery_person_ID,City,Zone,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Date,Time_Orderd,Time_Order_picked,Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
39254,INDORES03DEL01,Indore,03,29.0,4.6,22.751857,75.866699,22.821857,75.936699,20-03-2022,19:45,19:55,Fog,Jam,0,Buffet,motorcycle,1.0,No,Metropolitian,36

In [101]:
df['Delivery_person_ID'].str[-2:]

0        01
1        01
2        03
3        02
4        02
         ..
41939    01
41940    01
41941    03
41942    01
41943    02
Name: Delivery_person_ID, Length: 41944, dtype: object

In [102]:
agent = df['Delivery_person_ID'].str[-2:].str.strip()   

df.insert(3 , "Delivery_Agent" , agent)

In [103]:
df['Restaurant_latitude'] = df['Restaurant_latitude'].apply(lambda x : -x if x < 0 else x)

df['Restaurant_longitude'] = df['Restaurant_longitude'].apply(lambda x : -x if x < 0 else x)

In [104]:
df.shape

(41944, 22)

In [105]:
px.scatter_geo(
    df,
    lat="Restaurant_latitude",
    lon="Restaurant_longitude"
)

In [106]:
px.scatter_geo(
    df,
    lat="Delivery_location_latitude",
    lon="Delivery_location_longitude"
)

In [107]:
df.isna().sum().loc[lambda x : x > 0]

Delivery_person_Age        1719
Delivery_person_Ratings    1763
Time_Orderd                1600
Weather_conditions          569
Road_traffic_density        555
multiple_deliveries         905
Festival                    215
City_Type                  1114
dtype: int64

In [108]:
df['Delivery_person_Age'].describe()

count    40225.000000
mean        29.563083
std          5.812261
min         15.000000
25%         25.000000
50%         30.000000
75%         35.000000
max         50.000000
Name: Delivery_person_Age, dtype: float64

In [109]:
df['Delivery_person_Age'] = df['Delivery_person_Age'].fillna(df['Delivery_person_Age'].mean())

In [110]:
df.isna().sum().loc[lambda x : x > 0]

Delivery_person_Ratings    1763
Time_Orderd                1600
Weather_conditions          569
Road_traffic_density        555
multiple_deliveries         905
Festival                    215
City_Type                  1114
dtype: int64

In [111]:
# Converting DType of Order_Date from object to datetime
df['Order_Date'] = pd.to_datetime(df['Order_Date'] , format='mixed')

In [112]:
# Checking what irrelavant values present in Time_Order_picked feature
invalid_mask_time_ordered = pd.to_datetime(df['Time_Orderd'], errors='coerce').isna()

wrong_values_to = df.loc[invalid_mask_time_ordered, 'Time_Orderd']
wrong_values_to.value_counts()

C:\Users\LeoML\AppData\Local\Temp\ipykernel_22580\2467684873.py:2: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

Time_Orderd
0.833333333    410
1              396
0.958333333    389
0.791666667    387
0.875          378
0.916666667    369
0.75           367
0.416666667    191
0.458333333    177
0.5            175
0.375          167
0.625           79
0.541666667     74
0.583333333     63
0.708333333     61
0.666666667     46
Name: count, dtype: int64

In [113]:
# Function for time correction as there present 24:05 which is not a valid one so converting into 00:05
def correct_time(t):
    if pd.isna(t):
        return t
    if t.startswith("24:"):
        return "00:"+t.split(":")[1]
    return t

df['Time_Order_picked'] = df['Time_Order_picked'].apply(correct_time)

In [114]:
# Checking what irrelavant values present in Time_Order_picked feature
invalid_mask_time_order_picked = pd.to_datetime(df['Time_Order_picked'], errors='coerce').isna()

wrong_values_top = df.loc[invalid_mask_time_order_picked, 'Time_Order_picked']
wrong_values_top.value_counts()

C:\Users\LeoML\AppData\Local\Temp\ipykernel_22580\837461676.py:2: UserWarning:

Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.

Time_Order_picked
0.833333333    417
1              401
0.916666667    391
0.75           384
0.875          382
0.791666667    376
0.958333333    374
0.375          191
0.416666667    185
0.5            167
0.458333333    137
0.625           92
0.666666667     83
0.541666667     75
0.583333333     75
0.708333333     63
Name: count, dtype: int64

In [115]:
# Converting Time_Ordered and Time_Order_picked feature to datetime and also removing irrelavant values like (0.875 , 0.75 , 1 , etc) using `errors = 'coerce'`

df['Time_Orderd'] = pd.to_datetime(df['Time_Orderd'],
            format="%H:%M",
            errors='coerce').dt.time

df['Time_Order_picked'] = pd.to_datetime(df['Time_Order_picked'],
            format="%H:%M",
            errors='coerce').dt.time

In [116]:
# Creating order_datetime from Order_Date + Time_Ordered
order_datetime = pd.to_datetime(
    df['Order_Date'].astype('str') + " " + df['Time_Orderd'].astype('str'),
    errors='coerce'
)

df.insert(10 , "Order_Datetime" , order_datetime)

# Creating order_datetime from Order_Date + Time_Order_picked
Pickup_Datetime = pd.to_datetime(
    df['Order_Date'].astype('str') + " " + df['Time_Order_picked'].astype('str'),
    errors='coerce'
)

df.insert(11 , "Pickup_Datetime" , Pickup_Datetime)

In [117]:
# Some of the pickup done overnight (00:05 or 00:10)
mask = df['Pickup_Datetime'] < df['Order_Datetime']

df.loc[mask , 'Pickup_Datetime'] = df.loc[mask , 'Pickup_Datetime'] + pd.Timedelta(days = 1)

In [118]:
# Droping Order_Date , Time_Ordered , Time_Order_Picked as we have designed new freatures from them
df.drop(columns=['Order_Date' , "Time_Orderd" , "Time_Order_picked"] , inplace=True)

In [119]:
# Prep Time 
prep_time_min = ((df['Pickup_Datetime'] - df['Order_Datetime']).dt.total_seconds()/60)

df.insert(12 , "Prep_Time(min)" , prep_time_min)

In [120]:
# Droping these rows because imputation is risky
df.drop(index=df[df['Order_Datetime'].isna() & df['Pickup_Datetime'].isna()].index  , inplace=True)

In [121]:
# Statistical Information of Prep Time Feature
df['Prep_Time(min)'].describe()

count    32969.000000
mean         9.974067
std          4.087073
min          5.000000
25%          5.000000
50%         10.000000
75%         15.000000
max         15.000000
Name: Prep_Time(min), dtype: float64

In [122]:
# Median Prep Time
median_prep_time = df['Prep_Time(min)'].median()

# imputing the values of Order_Datetime with Pickup_Time Order_Datetime - median 
mask1 = df['Order_Datetime'].isna() 
df.loc[mask1 , "Order_Datetime"] = df.loc[mask1 , "Pickup_Datetime"] - pd.Timedelta(minutes=median_prep_time)

# imputing the values of Pickup_time with Order_Datetime + median 
mask2 = df['Pickup_Datetime'].isna()
df.loc[mask2 , 'Pickup_Datetime'] = df.loc[mask2 , "Order_Datetime"] + pd.Timedelta(minutes=median_prep_time)

In [123]:
# updating the Prep Time 
df['Prep_Time(min)'] = (df['Pickup_Datetime'] - df['Order_Datetime']).dt.total_seconds()/60

In [124]:
df.sample()

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
6540,KNPRES01DEL03,Kanpur,01,03,29.0,4.9,26.483672,80.320708,26.573672,80.410708,2022-02-18 22:50:00,2022-02-18 23:05:00,15.0,Fog,Low,1,Snack,motorcycle,NaN,No,Urban,26

In [125]:
# These Features are very important for both analysis and prediction and all of them contains null value and when imputing them with some mode (random way) will decrease the efficiency of the model and imputation will become unreliable 


df.drop(index=df[df['Delivery_person_Ratings'].isna() & df['Weather_conditions'].isna() & df['Road_traffic_density'].isna() & df['multiple_deliveries'].isna()].index , inplace=True)


df.drop(index=df[df['Delivery_person_Ratings'].isna() & df['Weather_conditions'].isna() & df['Road_traffic_density'].isna()].index , inplace=True)

In [126]:
# Fill missing values in 'City_Type' using group-wise mode based on 'City'
df['City_Type'] = df.groupby('City')['City_Type']\
        .transform(lambda x : x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))

In [127]:
df['Time_taken (min)'].describe()

count    41354.000000
mean        26.302341
std          9.378156
min         10.000000
25%         19.000000
50%         26.000000
75%         32.000000
max         54.000000
Name: Time_taken (min), dtype: float64

In [128]:
df['Delivery_person_Ratings'].mean()

np.float64(4.632457188371167)

In [129]:
mask3 = df[df['Delivery_person_Ratings'] == 6.0].index
df.loc[mask3 , 'Delivery_person_Ratings'] = np.nan

In [130]:
df['Delivery_person_Ratings'] = df.groupby('City_Type')['Delivery_person_Ratings'].transform(lambda x: x.fillna(x.median()))

In [131]:
df['Delivery_person_Ratings'].isna().sum()

np.int64(0)

In [132]:
indi = df[df['Weather_conditions'].isna()].index

In [133]:
df['Weather_conditions'] = df.groupby("City")['Weather_conditions'].transform(lambda x : x.fillna(x.mode()[0]))

In [134]:
df.loc[indi , 'Weather_conditions'].value_counts()

Weather_conditions
Sandstorms    29
Stormy        22
Cloudy        14
Fog           13
Windy          7
Sunny          4
Name: count, dtype: int64

In [135]:
indi2 = df[df['Road_traffic_density'].isna()].index

In [136]:
indi2

Index([ 2172,  2647,  2691,  3274,  4306,  4724,  4900,  5165,  5397,  5858,
        8404,  8726,  8760,  9282, 10014, 10220, 11109, 11286, 12173, 12540,
       12955, 13700, 13734, 14634, 14779, 15437, 15757, 16279, 17454, 17833,
       18645, 19531, 19618, 20514, 20625, 21520, 21625, 21768, 21786, 22309,
       22928, 23266, 23823, 23990, 24521, 24786, 24966, 25060, 25224, 25728,
       25785, 26068, 26665, 27175, 27291, 28139, 28723, 29403, 29736, 30548,
       30858, 31916, 32161, 33144, 34125, 34664, 34971, 34982, 35558, 35948,
       35957, 37012, 37067, 37944, 38714, 39420],
      dtype='int64')

In [137]:
df['Road_traffic_density'] = df.groupby('City_Type')['Road_traffic_density'].transform(lambda x : x.fillna(x.mode()[0]))

In [138]:
df.loc[indi2 , 'Road_traffic_density'].value_counts()

Road_traffic_density
Jam    56
Low    20
Name: count, dtype: int64

In [139]:
indi3 = df[df['multiple_deliveries'].isna()].index

In [140]:
df['multiple_deliveries'] = df['multiple_deliveries'].fillna(df['multiple_deliveries'].median())

In [141]:
df.loc[indi3 , 'multiple_deliveries']

8        1.0
67       1.0
76       1.0
116      1.0
124      1.0
        ...
41365    1.0
41372    1.0
41470    1.0
41538    1.0
41636    1.0
Name: multiple_deliveries, Length: 889, dtype: float64

In [142]:
df['Festival'] = df['Festival'].transform(lambda x : x.fillna(x.mode()[0]))

In [143]:
df.isna().sum()

Delivery_person_ID             0
City                           0
Zone                           0
Delivery_Agent                 0
Delivery_person_Age            0
Delivery_person_Ratings        0
Restaurant_latitude            0
Restaurant_longitude           0
Delivery_location_latitude     0
Delivery_location_longitude    0
Order_Datetime                 0
Pickup_Datetime                0
Prep_Time(min)                 0
Weather_conditions             0
Road_traffic_density           0
Vehicle_condition              0
Type_of_order                  0
Type_of_vehicle                0
multiple_deliveries            0
Festival                       0
City_Type                      0
Time_taken (min)               0
dtype: int64

In [144]:
df['Zone'] = df['Zone'].astype('Int32')

In [145]:
df.sample()

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
6107,RANCHIRES04DEL02,Ranchi,4,02,20.0,4.9,23.359033,85.325347,23.489033,85.455347,2022-02-03 17:55:00,2022-02-03 18:05:00,10.0,Windy,Medium,0,Snack,motorcycle,1.0,No,Metropolitian,30

In [146]:
df

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Delivery_person_Ratings,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
0,DEHRES17DEL01,Dehradun,17,01,36.0,4.2,30.327968,78.046106,30.397968,78.116106,2022-12-02 21:55:00,2022-12-02 22:10:00,15.0,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,KOCRES16DEL01,Kochi,16,01,21.0,4.7,10.003064,76.307589,10.043064,76.347589,2022-02-13 14:55:00,2022-02-13 15:05:00,10.0,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,PUNERES13DEL03,Pune,13,03,23.0,4.7,18.562450,73.916619,18.652450,74.006619,2022-04-03 17:30:00,2022-04-03 17:40:00,10.0,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,LUDHRES15DEL02,Ludhiana,15,02,34.0,4.3,30.899584,75.809346,30.919584,75.829346,2022-02-13 09:20:00,2022-02-13 09:30:00,10.0,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,KNPRES14DEL02,Kanpur,14,02,24.0,4.7,26.463504,80.372929,26.593504,80.502929,2022-02-14 19:50:00,2022-02-14 20:05:00,15.0,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41939,RANCHIRES16DEL01,Ranchi,16,01,35.0,4.2,23.371292,85.327872,23.481292,85.437872,2022-08-03 21:45:00,2022-08-03 21:55:00,10.0,Windy,Jam,2,Drinks,motorcycle,1.0,No,Metropolitian,33
41940,JAPRES04DEL01,Jaipur,4,01,30.0,4.8,26.902328,75.794257,26.912328,75.804257,2022-03-24 11:35:00,2022-03-24 11:45:00,10.0,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
41941,CHENRES08DEL03,Chennai,8,03,30.0,4.9,13.022394,80.242439,13.052394,80.272439,2022-11-03 23:50:00,2022-11-04 00:05:00,15.0,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
41942,COIMBRES11DEL01,Coimbatore,11,01,20.0,4.7,11.001753,76.986241,11.041753,77.026241,2022-07-03 13:35:00,2022-07-03 13:40:00,5.0,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
41943,RANCHIRES09DEL02,Ranchi,9,02,23.0,4.9,23.351058,85.325731,23.431058,85.405731,2022-02-03 17:10:00,2022-02-03 17:15:00,5.0,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

---

**Changing Data Type**

In [147]:
df['Delivery_Agent'] = df['Delivery_Agent'].astype('Int32')

In [148]:
df['Delivery_person_Age'] = df['Delivery_person_Age'].astype(int)

In [149]:
age_group = pd.cut(
    df['Delivery_person_Age'],
    bins=[14 , 25 , 35 , 50],
    labels=['Young' , 'Adult' , 'Senior'])

In [150]:
df.insert(5 , "Age_Group" , age_group)

In [151]:
delivery_rating_group = pd.cut(
    df['Delivery_person_Ratings'],
    bins=[0 , 3, 4 , 5],
    labels=['Low' , 'Medium' , 'High']
)

In [152]:
df.insert(7 , "Delivery_Person_Rating_Group" , delivery_rating_group)

In [153]:
df

,Delivery_person_ID,City,Zone,Delivery_Agent,Delivery_person_Age,Age_Group,Delivery_person_Ratings,Delivery_Person_Rating_Group,Restaurant_latitude,Restaurant_longitude,Delivery_location_latitude,Delivery_location_longitude,Order_Datetime,Pickup_Datetime,Prep_Time(min),Weather_conditions,Road_traffic_density,Vehicle_condition,Type_of_order,Type_of_vehicle,multiple_deliveries,Festival,City_Type,Time_taken (min)
0,DEHRES17DEL01,Dehradun,17,1,36,Senior,4.2,High,30.327968,78.046106,30.397968,78.116106,2022-12-02 21:55:00,2022-12-02 22:10:00,15.0,Fog,Jam,2,Snack,motorcycle,3.0,No,Metropolitian,46
1,KOCRES16DEL01,Kochi,16,1,21,Young,4.7,High,10.003064,76.307589,10.043064,76.347589,2022-02-13 14:55:00,2022-02-13 15:05:00,10.0,Stormy,High,1,Meal,motorcycle,1.0,No,Metropolitian,23
2,PUNERES13DEL03,Pune,13,3,23,Young,4.7,High,18.562450,73.916619,18.652450,74.006619,2022-04-03 17:30:00,2022-04-03 17:40:00,10.0,Sandstorms,Medium,1,Drinks,scooter,1.0,No,Metropolitian,21
3,LUDHRES15DEL02,Ludhiana,15,2,34,Adult,4.3,High,30.899584,75.809346,30.919584,75.829346,2022-02-13 09:20:00,2022-02-13 09:30:00,10.0,Sandstorms,Low,0,Buffet,motorcycle,0.0,No,Metropolitian,20
4,KNPRES14DEL02,Kanpur,14,2,24,Young,4.7,High,26.463504,80.372929,26.593504,80.502929,2022-02-14 19:50:00,2022-02-14 20:05:00,15.0,Fog,Jam,1,Snack,scooter,1.0,No,Metropolitian,41
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41939,RANCHIRES16DEL01,Ranchi,16,1,35,Adult,4.2,High,23.371292,85.327872,23.481292,85.437872,2022-08-03 21:45:00,2022-08-03 21:55:00,10.0,Windy,Jam,2,Drinks,motorcycle,1.0,No,Metropolitian,33
41940,JAPRES04DEL01,Jaipur,4,1,30,Adult,4.8,High,26.902328,75.794257,26.912328,75.804257,2022-03-24 11:35:00,2022-03-24 11:45:00,10.0,Windy,High,1,Meal,motorcycle,0.0,No,Metropolitian,32
41941,CHENRES08DEL03,Chennai,8,3,30,Adult,4.9,High,13.022394,80.242439,13.052394,80.272439,2022-11-03 23:50:00,2022-11-04 00:05:00,15.0,Cloudy,Low,1,Drinks,scooter,0.0,No,Metropolitian,16
41942,COIMBRES11DEL01,Coimbatore,11,1,20,Young,4.7,High,11.001753,76.986241,11.041753,77.026241,2022-07-03 13:35:00,2022-07-03 13:40:00,5.0,Cloudy,High,0,Snack,motorcycle,1.0,No,Metropolitian,26
41943,RANCHIRES09DEL02,Ranchi,9,2,23,Young,4.9,High,23.351058,85.325731,23.431058,85.405731,2022-02-03 17:10:00,2022-02-03 17:15:00,5.0,Fog,Medium,2,Snack,scooter,1.0,No,Metropolitian,36

In [154]:
df['Delivery_person_Ratings'].value_counts().sort_index()

Delivery_person_Ratings
1.0      33
2.5      18
2.6      20
2.7      21
2.8      17
2.9      18
3.0       6
3.1      28
3.2      26
3.3      23
3.4      32
3.5     236
3.6     194
3.7     203
3.8     218
3.9     176
4.0     998
4.1    1323
4.2    1331
4.3    1301
4.4    1245
4.5    3066
4.6    6394
4.7    7738
4.8    6556
4.9    6467
5.0    3666
Name: count, dtype: int64

In [155]:
df['Delivery_person_Ratings'] = df['Delivery_person_Ratings'].astype('float32')

In [156]:
df['Vehicle_condition'].value_counts()

Vehicle_condition
1    13792
2    13745
0    13741
3       76
Name: count, dtype: int64

In [157]:
mapping = {
    0:"poor",
    1:"Average",
    2:"Good",
    3:"Excellent",
}

df['Vehicle_condition'] = df['Vehicle_condition'].map(mapping)

In [158]:
df['Vehicle_condition']

0           Good
1        Average
2        Average
3           poor
4        Average
          ...
41939       Good
41940    Average
41941    Average
41942       poor
41943       Good
Name: Vehicle_condition, Length: 41354, dtype: object

In [159]:
df['Prep_Time(min)'] = df['Prep_Time(min)'].astype('Float32')

In [160]:
df['multiple_deliveries'] = df['multiple_deliveries'].astype('Int8')

In [161]:
df['Prep_Time(min)'] = df['Prep_Time(min)'].astype('Int16')

In [162]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 41354 entries, 0 to 41943
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Delivery_person_ID            41354 non-null  object
 1   City                          41354 non-null  object
 2   Zone                          41354 non-null  Int32
 3   Delivery_Agent                41354 non-null  Int32
 4   Delivery_person_Age           41354 non-null  int64
 5   Age_Group                     41354 non-null  category
 6   Delivery_person_Ratings       41354 non-null  float32
 7   Delivery_Person_Rating_Group  41354 non-null  category
 8   Restaurant_latitude           41354 non-null  float64
 9   Restaurant_longitude          41354 non-null  float64
 10  Delivery_location_latitude    41354 non-null  float64
 11  Delivery_location_longitude   41354 non-null  float64
 12  Order_Datetime                41354 non-null  datetime64[ns]
 13  Pickup_Datetime               41354 non-null  datetime64[ns]
 14  Prep_Time(min)                41354 non-null  Int16
 15  Weather_conditions            41354 non-null  object
 16  Road_traffic_density          41354 non-null  object
 17  Vehicle_condition             41354 non-null  object
 18  Type_of_order                 41354 non-null  object
 19  Type_of_vehicle               41354 non-null  object
 20  multiple_deliveries           41354 non-null  Int8
 21  Festival                      41354 non-null  object
 22  City_Type                     41354 non-null  object
 23  Time_taken (min)              41354 non-null  int64
dtypes: Int16(1), Int32(2), Int8(1), category(2), datetime64[ns](2), float32(1), float64(4), int64(2), object(9)
memory usage: 7.5+ MB

In [163]:
df.isna().sum()

Delivery_person_ID              0
City                            0
Zone                            0
Delivery_Agent                  0
Delivery_person_Age             0
Age_Group                       0
Delivery_person_Ratings         0
Delivery_Person_Rating_Group    0
Restaurant_latitude             0
Restaurant_longitude            0
Delivery_location_latitude      0
Delivery_location_longitude     0
Order_Datetime                  0
Pickup_Datetime                 0
Prep_Time(min)                  0
Weather_conditions              0
Road_traffic_density            0
Vehicle_condition               0
Type_of_order                   0
Type_of_vehicle                 0
multiple_deliveries             0
Festival                        0
City_Type                       0
Time_taken (min)                0
dtype: int64

In [165]:
df.shape

(41354, 24)

In [164]:
df.to_csv("data/Cleaned Delivery Dataset.csv" , index=False)